theme: jekyll-theme-dinky
title: David B Dean
linkedin_url: https://linkedin.com/in/davidbdean
resume_url: /assets/David%20Dean%20Resume%202023.pdf
email: ddean@ieee.org
scholar_url: https://scholar.google.com.au/citations?user=RG75LQYAAAAJ
osm_url: https://www.openstreetmap.org/user/David%20Dean
repository: dbdean/dbdean.github.io
mastodon_url: https://aus.social/@dbdean
