# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: David B Dean
description: >- # this means to ignore newlines until "baseurl:"
I’m a machine learning leader, researcher and data engineer with 19+ years of
experience in developing and improving state-of-the art machine-learning
research algorithms and turning them into useful, reusable code that can make
life easier for researchers, software engineers, and everyone else!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dbdean.com" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_url: https://linkedin.com/in/davidbdean
resume_url: /assets/David%20Dean%20Resume%202018.pdf
email: ddean@ieee.org
scholar_url: https://scholar.google.com.au/citations?user=RG75LQYAAAAJ
osm_url: https://www.openstreetmap.org/user/David%20Dean

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
